services:
  nuxt-app:
    image: node:18-alpine
    container_name: Nuxt3-App_Updo
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
